### Exploratory Data Analysis

Understanding the dataset to explore how the data is present in the database and if there is a need of creating some aggregrated tables that can help with:

* Vendor Selection for profitability
* Product Pricing optimization

In [1]:
import pandas as pd
import sqlite3

#database connection
conn = sqlite3.connect('inventory.db')

In [4]:
## checking tables in database

tables = pd.read_sql_query(" SELECT name FROM sqlite_master where type='table'",conn)
tables

                         name
0  begin_inventory-checkpoint
1             begin_inventory
2               end_inventory
3             purchase_prices
4              vendor_invoice

In [ ]:
pd.read_sql("select count(*) from purchases",conn)

   count(*)
0   2372474

In [ ]:
for table in tables:
    print('-'*50,f'{table}','-'*50)
    print('count of records:',pd.read_sql("select count(*) from purchase_prices"))